name: Standard PHP checks

on: [push]

jobs:
  build:
      runs-on: ubuntu-latest
      strategy:
        fail-fast: false
        matrix:
          php-versions: ['7.2', '7.3', '7.4']
  
      steps:
        - uses: actions/checkout@v1

        - name: Init PHP Versions
          uses: shivammathur/setup-php@v2
          with:
            php-version: ${{ matrix.php-versions }}
    
        - name: Check syntax error in php files
          run: find ./* -not -path "**/vendor/*" -type f -name '*.php' -print0 | xargs -0 -L 1 -P 4 -- php -l
        
        - name: Validate composer.json and composer.lock
          run:  composer validate -d ./themes/twentytwenty

        - name: Install dependencies
          run:  composer install --prefer-dist --no-progress --no-suggest  -d ./themes/twentytwenty
    
        - name: Run Code sniffs
          run: composer cs -d ./themes/twentytwenty
          if: always()
    
        - name: Run Psalm
          run: composer psalm -d ./themes/twentytwenty
          if: always()